[package]
name = "wallet-storage-mysql"
version = "0.1.0"
edition = "2021"
license = "SEE LICENSE IN license.md"

[lib]
path = "src/lib.rs"

[dependencies]
wallet-storage = { path = "../wallet-storage", features = ["mysql"] }
